name: Publish Bolinette Data to pypi.org

on:
  push:
    tags:
      - data-*

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Install dependencies
        run: |
          cp bolinette/data/pyproject.toml pyproject.toml
          rm poetry.lock
          pip install --upgrade pip wheel poetry
          poetry install
      - name: Build and publish version ${{ steps.get_version.outputs.VERSION }}
        run: |
          poetry build
          poetry publish -r pypi -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
