name: Publish Bolinette Web to pypi.org

on:
  push:
    tags:
      - web-*

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Initialize project config
        run: |
          cp bolinette/web/pyproject.toml pyproject.toml
          rm poetry.lock
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Setup local virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - name: Install project dependencies
        run: |
          poetry install
      - name: Build version ${{ steps.get_version.outputs.VERSION }}
        run: |
          poetry build
      - name: Publish version ${{ steps.get_version.outputs.VERSION }}
        run: |
          poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
